USE KAKAO_T;

CREATE TABLE PASSENGER_ID
(
USER_NUM INT NOT NULL,
USER_ID VARCHAR(20) NOT NULL,
PRIMARY KEY(USER_NUM),
FOREIGN KEY(USER_NUM) REFERENCES PASSENGER(USER_NUM)
);

CREATE TABLE PASSENGER(
USER_NUM INT NOT NULL,
USER_PW VARCHAR(20) NOT NULL,
USER_NAME VARCHAR(5) NOT NULL,
USER_PHONE_NUM VARCHAR(15) NOT NULL,
USER_BIRTHDAY DATE NOT NULL,
USER_ACCUMM INT NULL,
PRIMARY KEY(USER_NUM)
);

CREATE TABLE BOARD(
POST_NUM INT NOT NULL,
USER_NUM INT NOT NULL,
POST_DATE DATE NOT NULL,
POST_PW VARCHAR(20) NULL,
POST_CONTENTS VARCHAR(100) NOT NULL,
PRIMARY KEY(POST_NUM),
FOREIGN KEY(USER_NUM) REFERENCES PASSENGER(USER_NUM)
ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE PASSENGER_COUPON(
USER_NUM INT NOT NULL,
COUPON_CODE INT NOT NULL,
PRIMARY KEY(USER_NUM, COUPON_CODE)
);

CREATE TABLE COUPON(
COUPON_CODE INT NOT NULL,
COUPONE_VALIDITY DATE NULL,
COUPONE_CONTENTS VARCHAR(100) NOT NULL,
PRIMARY KEY(COUPON_CODE)
);

CREATE TABLE CALLING (
   CALL_NUM INT(10) NOT NULL,
   USER_NUM VARCHAR(9) NOT NULL,
   DRIVER_ID VARCHAR(9),
   STARTPOINT VARCHAR(20),
   ENDPOINT VARCHAR(20),
   PAYMENT VARCHAR(10)
);

CREATE TABLE DRIVER (
   DRIVER_NUM INT(9) NOT NULL,
   DRIVER_BRITHDAY DATE,
   DRIVER_PHONE_NUM VARCHAR(15),
   BUSINESS_AREA VARCHAR(20),
   DRIVER_SCORE FLOAT,
   DRIVER_NAME VARCHAR(5)
);

CREATE TABLE DRIVER_CAR (
   DRIVER_NUM INT(9) NOT NULL,
   CAR_NUM VARCHAR(10) NOT NULL
);

CREATE TABLE HISTORY (
   CALL_NUM INT(10) NOT NULL,
   USER_NUM VARCHAR(9) NOT NULL,
   DRIVER_ID VARCHAR(9) NOT NULL,
   STARTPOINT VARCHAR(20) NOT NULL,
   ENDPOINT VARCHAR(20) NOT NULL,
   PAYMENT VARCHAR(10) NOT NULL,
   CAR_NUM INT(10) NOT NULL,
   DRIVE_DATE DATE NOT NULL
);


CREATE TABLE CAR(
CAR_NUM VARCHAR(20) NOT NULL,
CAR_TYPE VARCHAR(10),
CAR_GRADE char(3),
CAR_AGENCY VARCHAR(20),
REGIST_DATE DATE,
PRIMARY KEY (CAR_NUM)
);

-- 공급은 운수업체로부터 받을수도 있고 아닐수도 있다.
CREATE TABLE SUPPLY(
BUSINESS_NUM INTEGER(20) NOT NULL,
SUPPLY_NUM INTEGER(20) NOT NULL,
SUPPLY_DATE DATE,
PRIMARY KEY(BUSINESS_NUM, SUPPLY_NUM),
FOREIGN KEY(BUSINESS_NUM) REFERENCES COMPANY(BUSINESS_NUM)
);

-- 운수업체 테이블에서는 제약조건 딱히 없다.
CREATE TABLE COMPANY(
BUSINESS_NUM INTEGER(20) NOT NULL,
COMPANY_NAME VARCHAR(20),
COMPANY_PHONE_NUM VARCHAR(15),
COMPANY_ADDRESS VARCHAR(20),
BUSINESS_MANAGER VARCHAR(5),
PRIMARY KEY(BUSINESS_NUM)
);


